#!/usr/bin/env python3

import socket
import sys

HOST = '127.0.0.1'
PORT = 10000
s = socket.socket()

try:
    s.connect((HOST, PORT))
except ConnectionRefusedError:
    print("server not running")
    s.close()
    sys.exit(1)

try:
    msg = sys.argv[1]
except IndexError:
    print("no message given")
    sys.exit(2)

s.send(msg.encode())
s.close()
sys.exit()
