#!/usr/bin/env python3

import socket
import sys
import yaml

CONFIG_FILE = "/home/rilla/.config/ir_screensaver.yaml"

with open(CONFIG_FILE) as fh:
    config = yaml.load(fh)

s = socket.socket()

try:
    s.connect((config["host"], config["port"]))
except ConnectionRefusedError:
    print("server not running")
    s.close()
    sys.exit(1)

try:
    msg = sys.argv[1]
except IndexError:
    print("no message given")
    sys.exit(2)

s.send(msg.encode())
s.close()
sys.exit()
