#!/usr/bin/env python3

###############################################################################

CONFIG_FILE = "/home/rilla/code/python/ir_screensaver/example_config.yaml"

###############################################################################

import sys
import time

from helpers import read_config, init_procs

###############################################################################

def main ():
    config = read_config(CONFIG_FILE)
    procs = init_procs(config)

    for p in procs:
        p.start()

    while True:
        time.sleep(1)

if __name__ == "__main__":
    sys.exit(main())

#############################################################################
